export const examConstants = {
  SUBMIT_REQUEST: "EXAM_SUBMIT_REQUEST",
  SUBMIT_SUCCESS: "EXAM_SUBMIT_SUCCESS",
  SUBMIT_FAILURE: "EXAM_SUBMIT_FAILURE",

  EXAM_LIST_INFO_REQUEST: "EXAM_LIST_INFO_REQUEST",
  EXAM_LIST_INFO_SUCCESS: "EXAM_LIST_INFO_SUCCESS",
  EXAM_LIST_INFO_FAILURE: "EXAM_LIST_INFO_FAILURE",

  EXAM_SUMMARY_REQUEST: "EXAM_SUMMARY_REQUEST",
  EXAM_SUMMARY_SUCCESS: "EXAM_SUMMARY_SUCCESS",
  EXAM_SUMMARY_FAILURE: "EXAM_SUMMARY_FAILURE",

  CREATE_EXAM_REQUEST: "CREATE_EXAM_REQUEST",
  CREATE_EXAM_SUCCESS: "CREATE_EXAM_SUCCESS",
  CREATE_EXAM_FAILURE: "CREATE_EXAM_FAILURE"
};
