export const examResultConstants = {
  EXAM_RESULT_REQUEST: "EXAM_RESULT_REQUEST",
  EXAM_RESULT_SUCCESS: "EXAM_RESULT_SUCCESS",
  EXAM_RESULT_FAILURE: "EXAM_RESULT_FAILURE",

  EXAM_INFO_REQUEST: "EXAM_INFO_REQUEST",
  EXAM_INFO_SUCCESS: "EXAM_INFO_SUCCESS",
  EXAM_INFO_FAILURE: "EXAM_INFO_FAILURE",

  EXAM_AVERAGES_REQUEST: "EXAM_AVERAGES_REQUEST",
  EXAM_AVERAGES_SUCCESS: "EXAM_AVERAGES_SUCCESS",
  EXAM_AVERAGES_FAILURE: "EXAM_AVERAGES_FAILURE",
};
