export const instructorConstants = {
  INSTRUCTOR_INFO_REQUEST: "INSTRUCTOR_INFO_REQUEST",
  INSTRUCTOR_INFO_SUCCESS: "INSTRUCTOR_INFO_SUCCESS",
  INSTRUCTOR_INFO_FAILURE: "INSTRUCTOR_INFO_FAILURE",
};