export const taskConstants = {
  CREATE_REQUEST: "TASK_CREATE_REQUEST",
  CREATE_SUCCESS: "TASK_CREATE_SUCCESS",
  CREATE_FAILURE: "TASK_CREATE_FAILURE",

  TASKLIST_REQUEST: "TASKLIST_REQUEST",
  TASKLIST_SUCCESS: "TASKLIST_SUCCESS",
  TASKLIST_FAILURE: "TASKLIST_FAILURE",
};